name: API Tests
run-name: Running API tests 🧪
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm test
